// Copyright (c) 2025 Felipe Dominguez. MIT License. See LICENSE.
//
// Phase 10 batch 55 (2026-05-16): alert-channel weekly smoke run.
//
// Each registered alert channel can silently drift to "broken" status
// (rotated webhook URL, revoked API key, expired bot token, etc.). The
// only way to find out before a real incident is to exercise the channel
// periodically with a low-impact test payload.
//
// This module ships a `runChannelSmoke(channels, options)` helper plus
// a Markdown report formatter. The expected operator wiring is a weekly
// cron / scheduled job (scripts/registry-alert-channel-smoke.ts) that
// builds the channel set, calls this helper, and persists / emails /
// posts the report.
//
// Each channel receives a synthetic `info`-severity payload tagged as a
// smoke run. Channels that send via HTTP webhook still hit the upstream
// — operators should configure a dedicated "test" Slack channel or a
// PagerDuty maintenance window so on-call doesn't get paged for the
// smoke. The helper is INTENT-DECLARING (the payload's title clearly
// labels itself "[SMOKE]" so a human reading the alert can recognise it).
//
// Telemetry-shaped result allows the runner to upsert results into a
// table or emit them as a structured log line for monitoring.

import { randomUUID } from 'crypto';
import type Database from 'better-sqlite3';

import type {
  AlertChannel,
  AlertPayload,
} from './registry-cross-tenant-alert-hook';
import type {
  CrossTenantAdversarialPattern,
} from './registry-adversarial-discovery';

export interface ChannelSmokeOptions {
  /** Override the generated-at timestamp (for tests). */
  nowIso?: string;
  /**
   * When true, builds the payload and walks the channel list but never
   * invokes `send`. Useful for staging environments where actual delivery
   * isn't desired.
   */
  dryRun?: boolean;
  /**
   * Per-channel timeout in milliseconds. A channel that takes longer is
   * marked as failed with a `timeout` reason. Default: 5000.
   */
  perChannelTimeoutMs?: number;
}

export interface ChannelSmokeResultEntry {
  channelId: string;
  status: 'sent' | 'skipped' | 'failed' | 'dry_run';
  /** Milliseconds elapsed during send. */
  elapsedMs: number;
  errorMessage?: string;
}

export interface ChannelSmokeResult {
  totalChannels: number;
  sentCount: number;
  skippedCount: number;
  failedCount: number;
  dryRunCount: number;
  generatedAt: string;
  entries: ChannelSmokeResultEntry[];
  /**
   * Phase 11 batch 56: assigned at run-time so persistence can group rows
   * by smoke invocation. Stable across re-reads of the same result object.
   */
  runId: string;
}

/**
 * Builds the synthetic smoke payload. The pattern shape mirrors a real
 * cross-tenant adversarial pattern so that channel payload-formatters
 * don't need a separate code path.
 */
export function buildSmokeAlertPayload(generatedAt: string): AlertPayload {
  const pattern: CrossTenantAdversarialPattern = {
    severity: 'info',
    skill: 'platform',
    action: 'channel_smoke_run',
    failureReason: 'smoke_test',
    outcome: 'smoke_run',
    tenantCount: 0,
    totalCount: 0,
    perTenantCounts: {},
    firstSeen: generatedAt,
    lastSeen: generatedAt,
    windowDays: 0,
  } as CrossTenantAdversarialPattern;
  return {
    severity: 'info',
    title: '[SMOKE] Alert-channel weekly health check',
    description:
      'This is a synthetic test payload generated by the alert-channel smoke run. ' +
      'No action is required. If you receive this and the channel was expected to be ' +
      'disabled, check the smoke-run report for unexpected channel deliveries.',
    pattern,
    generatedAt,
  };
}

/**
 * Runs the smoke probe across every channel. Each channel's `send()`
 * is invoked with the synthetic payload; success/failure is captured
 * per channel. Errors are caught — one bad channel doesn't abort the
 * smoke for the others.
 */
export async function runChannelSmoke(
  channels: AlertChannel[],
  options: ChannelSmokeOptions = {},
): Promise<ChannelSmokeResult> {
  const generatedAt = options.nowIso ?? new Date().toISOString();
  const payload = buildSmokeAlertPayload(generatedAt);
  const timeoutMs = options.perChannelTimeoutMs ?? 5000;
  const entries: ChannelSmokeResultEntry[] = [];

  for (const channel of channels) {
    const started = Date.now();
    if (options.dryRun) {
      entries.push({ channelId: channel.id, status: 'dry_run', elapsedMs: 0 });
      continue;
    }
    try {
      // Per-channel timeout race. We rely on the channel's transport
      // honoring AbortSignal in real use; this race just prevents one
      // slow channel from blocking the whole smoke.
      await Promise.race([
        Promise.resolve(channel.send(payload)),
        new Promise<never>((_, reject) => {
          setTimeout(() => reject(new Error(`channel ${channel.id} smoke timeout after ${timeoutMs}ms`)), timeoutMs);
        }),
      ]);
      entries.push({
        channelId: channel.id, status: 'sent',
        elapsedMs: Date.now() - started,
      });
    } catch (err) {
      entries.push({
        channelId: channel.id, status: 'failed',
        elapsedMs: Date.now() - started,
        errorMessage: err instanceof Error ? err.message : String(err),
      });
    }
  }

  return {
    totalChannels: channels.length,
    sentCount: entries.filter((e) => e.status === 'sent').length,
    skippedCount: entries.filter((e) => e.status === 'skipped').length,
    failedCount: entries.filter((e) => e.status === 'failed').length,
    dryRunCount: entries.filter((e) => e.status === 'dry_run').length,
    generatedAt,
    entries,
    runId: randomUUID(),
  };
}

// Phase 11 batch 56 (2026-05-16): SQLite persistence for smoke results.
//
// Persists each channel entry as its own row keyed by (run_id, channel_id).
// The runner is expected to call persistChannelSmokeResult after
// runChannelSmoke; the migration at migrations/135_alert_channel_smoke_runs.sql
// must already be applied.
//
// Failed channels persist with their error message so an operator
// reviewing the trend table can see what specifically broke (without
// having to keep the Markdown reports).

export interface PersistedSmokeRow {
  runId: string;
  channelId: string;
  status: 'sent' | 'skipped' | 'failed' | 'dry_run';
  elapsedMs: number;
  errorMessage: string | null;
  generatedAt: string;
  createdAt: string;
}

export interface RecentSmokeOptions {
  /** Filter to a specific channel id. */
  channelId?: string;
  /** Filter to a specific status. */
  status?: 'sent' | 'skipped' | 'failed' | 'dry_run';
  /** Inclusive lower bound on generated_at (ISO timestamp). */
  since?: string;
  /** Maximum rows to return (default: 100). */
  limit?: number;
}

export function persistChannelSmokeResult(
  db: Database.Database,
  result: ChannelSmokeResult,
): void {
  const insert = db.prepare(`
    INSERT INTO chat_alert_channel_smoke_runs (
      run_id, channel_id, status, elapsed_ms, error_message, generated_at
    ) VALUES (?, ?, ?, ?, ?, ?)
    ON CONFLICT(run_id, channel_id) DO UPDATE SET
      status = excluded.status,
      elapsed_ms = excluded.elapsed_ms,
      error_message = excluded.error_message
  `);
  const tx = db.transaction((entries: ChannelSmokeResultEntry[]) => {
    for (const entry of entries) {
      insert.run(
        result.runId,
        entry.channelId,
        entry.status,
        entry.elapsedMs,
        entry.errorMessage ?? null,
        result.generatedAt,
      );
    }
  });
  tx(result.entries);
}

export function getRecentChannelSmokeResults(
  db: Database.Database,
  options: RecentSmokeOptions = {},
): PersistedSmokeRow[] {
  const where: string[] = [];
  const params: unknown[] = [];
  if (options.channelId) {
    where.push('channel_id = ?');
    params.push(options.channelId);
  }
  if (options.status) {
    where.push('status = ?');
    params.push(options.status);
  }
  if (options.since) {
    where.push('generated_at >= ?');
    params.push(options.since);
  }
  const whereClause = where.length > 0 ? `WHERE ${where.join(' AND ')}` : '';
  const limit = options.limit ?? 100;
  const stmt = db.prepare(`
    SELECT run_id, channel_id, status, elapsed_ms, error_message, generated_at, created_at
    FROM chat_alert_channel_smoke_runs
    ${whereClause}
    ORDER BY generated_at DESC, channel_id ASC
    LIMIT ?
  `);
  const rows = stmt.all(...params, limit) as Array<{
    run_id: string; channel_id: string; status: PersistedSmokeRow['status'];
    elapsed_ms: number; error_message: string | null;
    generated_at: string; created_at: string;
  }>;
  return rows.map((r) => ({
    runId: r.run_id, channelId: r.channel_id, status: r.status,
    elapsedMs: r.elapsed_ms, errorMessage: r.error_message,
    generatedAt: r.generated_at, createdAt: r.created_at,
  }));
}

/**
 * Per-channel health summary derived from the trend table. Reports the
 * percentage of successful smoke runs over a window. Operators use this
 * to spot channels that are intermittently failing (e.g., a webhook URL
 * with flaky DNS) which a single smoke run would miss.
 */
export interface ChannelHealthRow {
  channelId: string;
  totalRuns: number;
  sentCount: number;
  failedCount: number;
  successRate: number;
  lastStatus: 'sent' | 'skipped' | 'failed' | 'dry_run';
  lastGeneratedAt: string;
}

export function summarizeChannelHealth(
  db: Database.Database,
  options: { since?: string } = {},
): ChannelHealthRow[] {
  const where: string[] = [];
  const params: unknown[] = [];
  if (options.since) {
    where.push('generated_at >= ?');
    params.push(options.since);
  }
  const whereClause = where.length > 0 ? `WHERE ${where.join(' AND ')}` : '';
  const stmt = db.prepare(`
    SELECT channel_id, status, generated_at
    FROM chat_alert_channel_smoke_runs
    ${whereClause}
    ORDER BY channel_id ASC, generated_at DESC
  `);
  const rows = stmt.all(...params) as Array<{
    channel_id: string; status: ChannelHealthRow['lastStatus']; generated_at: string;
  }>;
  const byChannel = new Map<string, ChannelHealthRow>();
  for (const row of rows) {
    let entry = byChannel.get(row.channel_id);
    if (!entry) {
      entry = {
        channelId: row.channel_id,
        totalRuns: 0, sentCount: 0, failedCount: 0, successRate: 0,
        lastStatus: row.status, lastGeneratedAt: row.generated_at,
      };
      byChannel.set(row.channel_id, entry);
    }
    entry.totalRuns += 1;
    if (row.status === 'sent') entry.sentCount += 1;
    if (row.status === 'failed') entry.failedCount += 1;
  }
  for (const row of byChannel.values()) {
    row.successRate = row.totalRuns > 0 ? row.sentCount / row.totalRuns : 0;
  }
  return Array.from(byChannel.values()).sort((a, b) => a.successRate - b.successRate);
}

/**
 * Markdown report for the smoke result. Designed to be emailed to the
 * operator or appended to a docs/release/eval-evidence/* file by the
 * scheduled runner.
 */
export function formatChannelSmokeMarkdown(result: ChannelSmokeResult): string {
  const lines: string[] = [];
  lines.push(`# Alert-channel weekly smoke run`);
  lines.push(``);
  lines.push(`_Generated ${result.generatedAt}_`);
  lines.push(``);
  lines.push(`## Summary`);
  lines.push(``);
  lines.push(`- Channels probed: **${result.totalChannels}**`);
  lines.push(`- Sent: **${result.sentCount}**`);
  lines.push(`- Failed: **${result.failedCount}**`);
  lines.push(`- Dry-run: ${result.dryRunCount}`);
  lines.push(``);
  if (result.entries.length === 0) {
    lines.push(`_No channels registered — nothing to probe._`);
    return lines.join('\n');
  }
  lines.push(`## Per-channel result`);
  lines.push(``);
  lines.push(`| Channel | Status | Elapsed (ms) | Error |`);
  lines.push(`|---|---|---|---|`);
  for (const entry of result.entries) {
    lines.push(
      `| ${entry.channelId} | ${entry.status} | ${entry.elapsedMs} | ${entry.errorMessage ?? ''} |`,
    );
  }
  return lines.join('\n');
}
