/**
 * Video Study Service
 *
 * Deep-analyzes individual YouTube videos by combining transcript extraction
 * with Claude analysis. Produces:
 *   - Hook breakdown (first 30s: exact words, pacing, technique)
 *   - Content structure (section-by-section with timestamps)
 *   - Key moments (quotable/viral moments with timestamps)
 *   - Content ideas (inspired by this video, adapted for Felipe)
 *   - Reel/Short cuts (suggested clip points with timestamps)
 *
 * Used by:
 *   - /studyvideo <url> — Full video study
 *   - /transcribe <url> — Just get the transcript
 *   - Channel learner — Deep analysis of top-performing videos
 */
import Anthropic from '@anthropic-ai/sdk';
import fs from 'fs';
import path from 'path';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from 'docx';
import { config } from '../config';
import { logger } from '../utils/logger';
import { trackedCreate } from '../portal/anthropic-hook';
import { pushEvent } from '../portal/telemetry';
import {
  fetchTranscript,
  extractVideoId,
  formatTranscriptTimestamped,
  getHookSection,
  splitIntoSections,
  type TranscriptResult,
} from './youtube-transcript';
import { getDb } from './database';

const client = new Anthropic({
  apiKey: config.anthropic.apiKey,
  maxRetries: 3,
});

// ─── Types ──────────────────────────────────────────────────────────

export interface VideoStudyResult {
  videoId: string;
  title: string;
  channelName: string;
  transcriptAvailable: boolean;
  transcriptLanguage: string;
  transcriptLength: number;
  hookAnalysis: string;
  structureBreakdown: string;
  keyMoments: string[];
  contentIdeas: string[];
  reelCuts: ReelCut[];
  fullAnalysis: string;       // Complete Claude analysis text
  durationMs: number;
}

export interface ReelCut {
  startTimestamp: string;     // "2:15"
  endTimestamp: string;       // "2:45"
  description: string;        // What this clip covers
  hookSuggestion: string;     // Hook text for the reel
  estimatedDuration: string;  // "30s", "45s"
}

// ─── Transcript Cache (SQLite) ───────────────────────────────────────

function getCachedTranscript(videoId: string): {
  full_text: string;
  hook_text: string;
  title: string;
  channel_name: string;
  language: string;
  duration_seconds: number;
} | null {
  try {
    const db = getDb();
    return db.prepare(
      'SELECT full_text, hook_text, title, channel_name, language, duration_seconds FROM video_transcripts WHERE video_id = ?',
    ).get(videoId) as any;
  } catch {
    return null;
  }
}

function cacheTranscript(
  transcript: TranscriptResult,
  refChannelId?: number | null,
  source = 'manual',
): void {
  try {
    const db = getDb();
    db.prepare(`
      INSERT INTO video_transcripts
        (video_id, title, channel_name, language, full_text, hook_text,
         duration_seconds, is_auto_generated, segment_count, char_count,
         ref_channel_id, source)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      ON CONFLICT(video_id) DO UPDATE SET
        full_text = excluded.full_text,
        hook_text = excluded.hook_text,
        updated_at = datetime('now')
    `).run(
      transcript.videoId,
      transcript.title,
      transcript.channelName,
      transcript.language,
      transcript.fullText,
      getHookSection(transcript.segments, 30),
      transcript.durationSeconds,
      transcript.isAutoGenerated ? 1 : 0,
      transcript.segments.length,
      transcript.fullText.length,
      refChannelId ?? null,
      source,
    );
  } catch (err) {
    logger.warn({ err, videoId: transcript.videoId }, 'Failed to cache transcript');
  }
}

function cacheStudyResult(videoId: string, result: VideoStudyResult): void {
  try {
    const db = getDb();
    const transcriptRow = db.prepare(
      'SELECT id FROM video_transcripts WHERE video_id = ?',
    ).get(videoId) as { id: number } | undefined;

    db.prepare(`
      INSERT INTO video_studies
        (video_id, transcript_id, study_type, analysis_json,
         hook_analysis, structure_breakdown, key_moments, content_ideas, reel_cuts)
      VALUES (?, ?, 'full', ?, ?, ?, ?, ?, ?)
    `).run(
      videoId,
      transcriptRow?.id ?? null,
      JSON.stringify(result),
      result.hookAnalysis,
      result.structureBreakdown,
      JSON.stringify(result.keyMoments),
      JSON.stringify(result.contentIdeas),
      JSON.stringify(result.reelCuts),
    );
  } catch (err) {
    logger.warn({ err, videoId }, 'Failed to cache study result');
  }
}

// ─── Claude Analysis Prompts ─────────────────────────────────────────

const STUDY_SYSTEM_PROMPT = `You are a world-class content strategist analyzing a YouTube video's transcript to extract actionable insights.

You will receive the video's full transcript with timestamps. Analyze it thoroughly and provide:

1. **HOOK ANALYSIS** (first 30 seconds)
   - Exact opening words/phrases
   - What psychological trigger is used (curiosity, shock, identity, urgency, story)
   - Pacing: how fast do they get to the point?
   - Visual cues implied (if they reference what's on screen)
   - Grade: A/B/C/D with explanation

2. **CONTENT STRUCTURE**
   - Section-by-section breakdown with timestamps: [0:00-2:30] Introduction, [2:30-5:00] Point 1, etc.
   - How transitions between sections are handled
   - Where retention dips likely occur (long tangents, slow sections)
   - Where retention peaks (stories, reveals, pattern interrupts)

3. **KEY MOMENTS** (5-8 moments)
   - Timestamp + exact quote or paraphrase
   - Why it's notable (viral potential, strong insight, emotional peak, great one-liner)
   - How it could be adapted for PT-BR content

4. **CONTENT IDEAS** (3-5 ideas)
   - Ideas INSPIRED by this video that Felipe could create
   - Each with: title (PT-BR), format (YouTube/Reel/Short), hook, unique angle
   - These should NOT be copies — they should be Felipe's take using his fitness + commentary niches

5. **REEL/SHORT CUTS** (3-5 suggested clips)
   - Start timestamp → End timestamp
   - Description of the clip
   - Suggested hook text (PT-BR) for posting as a standalone Reel/Short
   - Estimated duration (aim for 30-60s)

FORMAT: Return valid JSON:
{
  "hook_analysis": "Detailed first-30s breakdown...",
  "structure_breakdown": "[0:00-1:30] Hook: Opens with...\n[1:30-4:00] Point 1: ...",
  "key_moments": [
    "[2:15] 'Exact quote or paraphrase' — Why it's notable...",
    ...
  ],
  "content_ideas": [
    "📹 TITLE (PT-BR) — Format: YouTube — Hook: '...' — Angle: ...",
    ...
  ],
  "reel_cuts": [
    {
      "startTimestamp": "2:15",
      "endTimestamp": "2:45",
      "description": "What this clip covers",
      "hookSuggestion": "Hook text in PT-BR for posting as standalone reel",
      "estimatedDuration": "30s"
    }
  ]
}

RULES:
- Be specific — cite exact timestamps and quotes from the transcript
- Content ideas MUST be in PT-BR (Brazilian Portuguese) for titles/hooks
- Reel cuts should be self-contained (make sense without the full video)
- Focus on ACTIONABLE insights — what can Felipe actually use?
- If transcript is auto-generated, account for possible transcription errors`;

/**
 * Full video study: transcript + deep Claude analysis.
 */
export async function studyVideo(
  videoIdOrUrl: string,
  options?: { skipCache?: boolean },
): Promise<VideoStudyResult> {
  const startTime = Date.now();
  const videoId = extractVideoId(videoIdOrUrl);
  if (!videoId) {
    throw new Error('Invalid YouTube video URL or ID');
  }

  // Check cache first
  if (!options?.skipCache) {
    const cached = getCachedStudy(videoId);
    if (cached) {
      logger.info({ videoId }, 'Returning cached video study');
      return cached;
    }
  }

  // Fetch transcript
  const transcript = await fetchTranscript(videoId);
  if (!transcript || transcript.fullText.length < 100) {
    throw new Error(
      `No transcript available for this video (${videoId}). The video may not have captions enabled.`,
    );
  }

  // Cache transcript
  cacheTranscript(transcript, null, 'study');

  // Prepare transcript for Claude (truncate very long ones)
  const maxTranscriptChars = 25000; // ~7K tokens, leaves room for analysis
  const transcriptText = transcript.fullText.length > maxTranscriptChars
    ? transcript.fullText.substring(0, maxTranscriptChars) + '\n\n[TRANSCRIPT TRUNCATED — video is very long]'
    : transcript.fullText;

  const timestampedText = formatTranscriptTimestamped(transcript.segments);
  const hookText = getHookSection(transcript.segments, 30);
  const sections = splitIntoSections(transcript.segments);

  // Build context for Claude
  const prompt = `Analyze this YouTube video:

📺 **"${transcript.title}"** by ${transcript.channelName}
⏱ Duration: ${Math.floor(transcript.durationSeconds / 60)}:${(transcript.durationSeconds % 60).toString().padStart(2, '0')}
🗣️ Language: ${transcript.language} ${transcript.isAutoGenerated ? '(auto-generated captions)' : '(manual captions)'}

FIRST 30 SECONDS (HOOK):
${hookText}

FULL TRANSCRIPT (with timestamps):
${timestampedText.substring(0, maxTranscriptChars)}

Provide the complete study analysis.`;

  const response = await trackedCreate(client, {
    model: config.anthropic.model, // Sonnet for quality
    max_tokens: 4096,
    system: STUDY_SYSTEM_PROMPT,
    messages: [{ role: 'user', content: prompt }],
    temperature: 0.4,
  }, 'video_study');

  let text = response.content
    .filter((b): b is Anthropic.TextBlock => b.type === 'text')
    .map((b) => b.text)
    .join('');

  text = text.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/i, '').trim();

  let analysis: any;
  try {
    analysis = JSON.parse(text);
  } catch {
    // If JSON parsing fails, treat the whole response as the analysis
    analysis = {
      hook_analysis: text,
      structure_breakdown: '',
      key_moments: [],
      content_ideas: [],
      reel_cuts: [],
    };
  }

  const result: VideoStudyResult = {
    videoId,
    title: transcript.title,
    channelName: transcript.channelName,
    transcriptAvailable: true,
    transcriptLanguage: transcript.language,
    transcriptLength: transcript.fullText.length,
    hookAnalysis: analysis.hook_analysis || '',
    structureBreakdown: analysis.structure_breakdown || '',
    keyMoments: Array.isArray(analysis.key_moments) ? analysis.key_moments : [],
    contentIdeas: Array.isArray(analysis.content_ideas) ? analysis.content_ideas : [],
    reelCuts: Array.isArray(analysis.reel_cuts) ? analysis.reel_cuts : [],
    fullAnalysis: text,
    durationMs: Date.now() - startTime,
  };

  // Cache result
  cacheStudyResult(videoId, result);

  pushEvent({
    ts: new Date().toISOString(),
    type: 'job',
    summary: `Video studied: "${transcript.title.substring(0, 40)}" — ${result.contentIdeas.length} ideas, ${result.reelCuts.length} reel cuts`,
  });

  return result;
}

/**
 * Quick transcript-only fetch (no Claude analysis).
 */
export async function getTranscript(videoIdOrUrl: string): Promise<TranscriptResult | null> {
  const videoId = extractVideoId(videoIdOrUrl);
  if (!videoId) return null;

  // Check cache
  const cached = getCachedTranscript(videoId);
  if (cached) {
    return {
      videoId,
      title: cached.title,
      channelName: cached.channel_name,
      language: cached.language,
      segments: [], // Not stored in cache (too large)
      fullText: cached.full_text,
      durationSeconds: cached.duration_seconds,
      isAutoGenerated: false,
    };
  }

  const transcript = await fetchTranscript(videoId);
  if (transcript) {
    cacheTranscript(transcript, null, 'manual');
  }
  return transcript;
}

/**
 * Get cached study result (if exists).
 */
function getCachedStudy(videoId: string): VideoStudyResult | null {
  try {
    const db = getDb();
    const row = db.prepare(
      'SELECT analysis_json FROM video_studies WHERE video_id = ? ORDER BY created_at DESC LIMIT 1',
    ).get(videoId) as { analysis_json: string } | undefined;

    if (!row) return null;
    return JSON.parse(row.analysis_json);
  } catch {
    return null;
  }
}

// ─── Batch Study for Channel Learner ─────────────────────────────────

/**
 * Fetch transcripts for the top N videos of a channel (by view count)
 * and extract deeper patterns including exact hook phrases, transitions,
 * storytelling beats, and pacing.
 *
 * Called from channel-learner to enrich pattern extraction.
 */
export async function deepAnalyzeTopVideos(
  channelName: string,
  videos: { videoId: string; title: string; viewCount: number }[],
  topN = 5,
): Promise<{
  transcriptCount: number;
  deepPatterns: string;       // Formatted for injection into the pattern extraction prompt
}> {
  // Sort by views, take top N
  const topVideos = [...videos]
    .sort((a, b) => b.viewCount - a.viewCount)
    .slice(0, topN);

  logger.info({ channelName, topN, videoCount: topVideos.length }, 'Deep-analyzing top videos with transcripts');

  const transcripts: { title: string; hookText: string; fullText: string }[] = [];

  for (const v of topVideos) {
    try {
      // Check cache first
      const cached = getCachedTranscript(v.videoId);
      if (cached) {
        transcripts.push({
          title: cached.title || v.title,
          hookText: cached.hook_text || '',
          fullText: cached.full_text.substring(0, 5000),
        });
        continue;
      }

      const transcript = await fetchTranscript(v.videoId);
      if (transcript && transcript.fullText.length > 50) {
        cacheTranscript(transcript, null, 'channel_analysis');
        transcripts.push({
          title: transcript.title,
          hookText: getHookSection(transcript.segments, 30),
          fullText: transcript.fullText.substring(0, 5000),
        });
      }
    } catch (err) {
      logger.debug({ err, videoId: v.videoId }, 'Transcript unavailable for top video');
    }

    // Rate limit
    await new Promise((r) => setTimeout(r, 1500));
  }

  if (transcripts.length === 0) {
    return { transcriptCount: 0, deepPatterns: '' };
  }

  // Build a compact transcript summary for the pattern extractor
  const deepPatterns = transcripts.map((t, i) => {
    return `\n--- TRANSCRIPT ${i + 1}: "${t.title}" ---
HOOK (first 30s): ${t.hookText}
BODY (first ~5000 chars): ${t.fullText}`;
  }).join('\n');

  logger.info({ channelName, transcriptCount: transcripts.length }, 'Deep analysis transcripts prepared');

  return {
    transcriptCount: transcripts.length,
    deepPatterns,
  };
}

// ─── Telegram Formatters ─────────────────────────────────────────────

export function formatStudyResult(result: VideoStudyResult): string {
  const esc = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const lines: string[] = [];

  lines.push(`📚 <b>Video Study: "${esc(result.title)}"</b>`);
  lines.push(`📺 ${esc(result.channelName)} · ${result.transcriptLanguage} · ${Math.round(result.transcriptLength / 1000)}K chars`);
  lines.push(`⏱ ${Math.round(result.durationMs / 1000)}s analysis time`);
  lines.push('');

  // Hook Analysis
  if (result.hookAnalysis) {
    lines.push(`🎣 <b>HOOK ANALYSIS</b>`);
    lines.push(esc(result.hookAnalysis.substring(0, 600)));
    lines.push('');
  }

  // Structure
  if (result.structureBreakdown) {
    lines.push(`🏗️ <b>CONTENT STRUCTURE</b>`);
    lines.push(esc(result.structureBreakdown.substring(0, 800)));
    lines.push('');
  }

  // Key Moments
  if (result.keyMoments.length > 0) {
    lines.push(`⭐ <b>KEY MOMENTS</b> (${result.keyMoments.length})`);
    for (const moment of result.keyMoments.slice(0, 5)) {
      lines.push(`  • ${esc(typeof moment === 'string' ? moment : JSON.stringify(moment))}`);
    }
    lines.push('');
  }

  // Content Ideas
  if (result.contentIdeas.length > 0) {
    lines.push(`💡 <b>CONTENT IDEAS</b> (${result.contentIdeas.length})`);
    for (const idea of result.contentIdeas) {
      lines.push(`  • ${esc(typeof idea === 'string' ? idea : JSON.stringify(idea))}`);
    }
    lines.push('');
  }

  // Reel Cuts
  if (result.reelCuts.length > 0) {
    lines.push(`🎬 <b>REEL/SHORT CUTS</b> (${result.reelCuts.length})`);
    for (const cut of result.reelCuts) {
      if (typeof cut === 'object' && cut.startTimestamp) {
        lines.push(`  ✂️ [${esc(cut.startTimestamp)} → ${esc(cut.endTimestamp)}] ${esc(cut.description)}`);
        if (cut.hookSuggestion) lines.push(`     🎣 "${esc(cut.hookSuggestion)}"`);
      } else {
        lines.push(`  ✂️ ${esc(String(cut))}`);
      }
    }
  }

  return lines.join('\n');
}

export function formatTranscriptMessage(transcript: TranscriptResult): string {
  const esc = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

  let msg = `📝 <b>Transcript: "${esc(transcript.title)}"</b>\n`;
  msg += `📺 ${esc(transcript.channelName)} · ${transcript.language}${transcript.isAutoGenerated ? ' (auto)' : ''}\n`;
  msg += `⏱ ${Math.floor(transcript.durationSeconds / 60)}:${(transcript.durationSeconds % 60).toString().padStart(2, '0')} · ${transcript.segments.length} segments · ${Math.round(transcript.fullText.length / 1000)}K chars\n\n`;

  // Show timestamped text (truncated for Telegram)
  const timestamped = formatTranscriptTimestamped(transcript.segments);
  msg += esc(timestamped.substring(0, 3500));

  if (timestamped.length > 3500) {
    msg += '\n\n<i>... transcript truncated. Full text saved to cache.</i>';
  }

  return msg;
}

// ─── DOCX Export ─────────────────────────────────────────────────────

export const IDEAS_DIR = '/home/dominguez/Desktop/IDEAS';

function sanitizeFilename(name: string): string {
  return name.replace(/[^a-zA-Z0-9_\-.\s]/g, '').replace(/\s+/g, '_').substring(0, 80);
}

/**
 * Save a transcript as a .docx Word file and return the file path.
 */
export async function saveTranscriptAsDocx(transcript: TranscriptResult): Promise<string> {
  const timestamped = formatTranscriptTimestamped(transcript.segments);

  const children: Paragraph[] = [
    new Paragraph({
      children: [new TextRun({ text: transcript.title, bold: true, size: 32 })],
      heading: HeadingLevel.HEADING_1,
    }),
    new Paragraph({
      children: [
        new TextRun({ text: `Channel: ${transcript.channelName}`, italics: true, size: 22 }),
        new TextRun({ text: `  |  Language: ${transcript.language}${transcript.isAutoGenerated ? ' (auto-generated)' : ''}`, italics: true, size: 22 }),
        new TextRun({ text: `  |  Duration: ${Math.floor(transcript.durationSeconds / 60)}:${(transcript.durationSeconds % 60).toString().padStart(2, '0')}`, italics: true, size: 22 }),
      ],
    }),
    new Paragraph({ text: '' }),
    new Paragraph({
      children: [new TextRun({ text: 'Full Transcript', bold: true, size: 28 })],
      heading: HeadingLevel.HEADING_2,
    }),
  ];

  // Add timestamped blocks
  for (const line of timestamped.split('\n')) {
    if (!line.trim()) continue;
    const tsMatch = line.match(/^\[(\d+:\d+)\]\s*(.*)/);
    if (tsMatch) {
      children.push(new Paragraph({
        children: [
          new TextRun({ text: `[${tsMatch[1]}] `, bold: true, size: 22, color: '666666' }),
          new TextRun({ text: tsMatch[2], size: 22 }),
        ],
        spacing: { after: 120 },
      }));
    } else {
      children.push(new Paragraph({ children: [new TextRun({ text: line, size: 22 })] }));
    }
  }

  const doc = new Document({
    sections: [{ children }],
  });

  const filename = `transcript_${sanitizeFilename(transcript.title)}_${transcript.videoId}.docx`;
  const filePath = path.join(IDEAS_DIR, filename);

  if (!fs.existsSync(IDEAS_DIR)) fs.mkdirSync(IDEAS_DIR, { recursive: true });
  const buffer = await Packer.toBuffer(doc);
  fs.writeFileSync(filePath, buffer);

  logger.info({ filePath, title: transcript.title }, 'Transcript saved as DOCX');
  return filePath;
}

/**
 * Save a video study as a .docx Word file and return the file path.
 */
export async function saveStudyAsDocx(result: VideoStudyResult): Promise<string> {
  const children: Paragraph[] = [
    new Paragraph({
      children: [new TextRun({ text: `Video Study: ${result.title}`, bold: true, size: 32 })],
      heading: HeadingLevel.HEADING_1,
    }),
    new Paragraph({
      children: [
        new TextRun({ text: `Channel: ${result.channelName}`, italics: true, size: 22 }),
        new TextRun({ text: `  |  Language: ${result.transcriptLanguage}`, italics: true, size: 22 }),
      ],
    }),
    new Paragraph({ text: '' }),
  ];

  const addSection = (title: string, content: string) => {
    children.push(new Paragraph({
      children: [new TextRun({ text: title, bold: true, size: 28 })],
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 240 },
    }));
    for (const line of content.split('\n')) {
      children.push(new Paragraph({
        children: [new TextRun({ text: line, size: 22 })],
        spacing: { after: 80 },
      }));
    }
  };

  addSection('Hook Analysis (First 30s)', result.hookAnalysis);
  addSection('Content Structure', result.structureBreakdown);

  if (result.keyMoments.length > 0) {
    addSection('Key Moments', result.keyMoments.map((m, i) => `${i + 1}. ${m}`).join('\n'));
  }
  if (result.contentIdeas.length > 0) {
    addSection('Content Ideas', result.contentIdeas.map((m, i) => `${i + 1}. ${m}`).join('\n'));
  }
  if (result.reelCuts.length > 0) {
    addSection('Reel/Short Cut Suggestions', result.reelCuts.map((m, i) => `${i + 1}. ${typeof m === 'string' ? m : `[${m.startTimestamp}-${m.endTimestamp}] ${m.description}`}`).join('\n'));
  }

  // Add full analysis as final section
  if (result.fullAnalysis) {
    addSection('Full Analysis', result.fullAnalysis);
  }

  const doc = new Document({
    sections: [{ children }],
  });

  const filename = `study_${sanitizeFilename(result.title)}_${result.videoId}.docx`;
  const filePath = path.join(IDEAS_DIR, filename);

  if (!fs.existsSync(IDEAS_DIR)) fs.mkdirSync(IDEAS_DIR, { recursive: true });
  const buffer = await Packer.toBuffer(doc);
  fs.writeFileSync(filePath, buffer);

  logger.info({ filePath, title: result.title }, 'Video study saved as DOCX');
  return filePath;
}
