// Copyright (c) 2025 Felipe Dominguez. MIT License. See LICENSE.

/**
 * YouTube Transcript Service
 *
 * Extracts video transcripts/captions from YouTube without external dependencies.
 * Uses YouTube's internal timedtext/caption API by:
 *   1. Fetching the video page HTML
 *   2. Extracting captionTracks from ytInitialPlayerResponse
 *   3. Fetching the captions XML
 *   4. Parsing into structured text with timestamps
 *
 * Works for any public video with auto-generated or manual captions.
 * No API key required — uses the same endpoints YouTube's player uses.
 */
import { execFile } from 'child_process';
import { promisify } from 'util';
import fs from 'fs';
import os from 'os';
import path from 'path';
import { logger } from '../utils/logger';
import { assertSafeExternalUrl } from '../security/url-guard';
import { contentLogFingerprint, safeContentLogErrorFields } from './content-log-safety';

const execFileAsync = promisify(execFile);
const YT_DLP_PATH = path.join(os.homedir(), '.local/bin/yt-dlp');
const YOUTUBE_CAPTION_URL_POLICY = {
  allowedHostSuffixes: ['youtube.com', 'youtube-nocookie.com', 'googlevideo.com'],
};
const MAX_CAPTION_REDIRECTS = 3;

export type TranscriptFetchOptions = {
  abortSignal?: AbortSignal;
};

function throwIfTranscriptFetchAborted(abortSignal?: AbortSignal): void {
  if (!abortSignal?.aborted) return;
  if (abortSignal.reason instanceof Error) throw abortSignal.reason;
  throw Object.assign(new Error('content_transcript_fetch_cancelled'), {
    name: 'AbortError',
    code: 'CONTENT_CLIENT_DISCONNECTED',
  });
}

// ─── Types ──────────────────────────────────────────────────────────

export interface TranscriptSegment {
  text: string;
  start: number;     // seconds
  duration: number;   // seconds
}

export interface TranscriptResult {
  videoId: string;
  title: string;
  channelName: string;
  language: string;         // e.g. "en", "pt", "auto"
  segments: TranscriptSegment[];
  fullText: string;          // All segments joined as plain text
  durationSeconds: number;   // Total video duration
  isAutoGenerated: boolean;
}

export interface VideoStudyResult {
  transcript: TranscriptResult;
  hookAnalysis: string;       // First 30s breakdown
  structureBreakdown: string; // Section-by-section analysis
  keyMoments: string[];       // Quotable/notable moments
  contentIdeas: string[];     // Ideas inspired by this video
  reelCuts: string[];         // Suggested reel/short cut points
}

// ─── Video ID Extraction ─────────────────────────────────────────────

/**
 * Extract YouTube video ID from various URL formats:
 *   - https://www.youtube.com/watch?v=dQw4w9WgXcQ
 *   - https://youtu.be/dQw4w9WgXcQ
 *   - https://www.youtube.com/embed/dQw4w9WgXcQ
 *   - https://www.youtube.com/shorts/dQw4w9WgXcQ
 *   - plain video ID: dQw4w9WgXcQ
 */
export function extractVideoId(input: string): string | null {
  const trimmed = input.trim();

  // Plain video ID (11 chars, alphanumeric + dash + underscore)
  if (/^[a-zA-Z0-9_-]{11}$/.test(trimmed)) {
    return trimmed;
  }

  try {
    const url = assertSafeExternalUrl(trimmed, {
      allowedHosts: ['youtu.be'],
      allowedHostSuffixes: ['youtube.com', 'youtube-nocookie.com'],
    });

    // youtube.com/watch?v=...
    if (url.hostname === 'youtube.com' || url.hostname.endsWith('.youtube.com')) {
      if (url.searchParams.has('v')) {
        return url.searchParams.get('v');
      }
    }

    if ((url.hostname === 'youtube-nocookie.com' || url.hostname.endsWith('.youtube-nocookie.com')) && url.searchParams.has('v')) {
      return url.searchParams.get('v');
    }

    // youtu.be/...
    if (url.hostname === 'youtu.be') {
      return url.pathname.slice(1).split('/')[0] || null;
    }

    // youtube.com/embed/... or youtube.com/shorts/...
    const pathMatch = url.pathname.match(/\/(?:embed|shorts|v)\/([a-zA-Z0-9_-]{11})/);
    if (pathMatch) return pathMatch[1];

  } catch {
    // Blocked/unsafe URLs should stay rejected. Only use the raw fallback for
    // non-URL input such as a bare video ID or pasted path fragment.
    if (/^[a-z][a-z0-9+.-]*:\/\//i.test(trimmed)) {
      return null;
    }

    // Not a URL — try regex on raw string.
    const idMatch = trimmed.match(/(?:v=|\/|youtu\.be\/)([a-zA-Z0-9_-]{11})/);
    if (idMatch) return idMatch[1];
  }

  return null;
}

// ─── Transcript Fetching ─────────────────────────────────────────────

const USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36';

export function assertSafeYouTubeCaptionUrl(rawUrl: string): URL {
  return assertSafeExternalUrl(rawUrl, YOUTUBE_CAPTION_URL_POLICY);
}

async function fetchYouTubeCaptionUrl(
  rawUrl: string,
  init: RequestInit = {},
  redirectsRemaining = MAX_CAPTION_REDIRECTS,
): Promise<Response> {
  // Residual accepted: caption URLs originate from YouTube player metadata,
  // and every redirect hop is re-allowlisted before fetch. This does not
  // locally resolve-and-pin DNS for the selected host.
  const url = assertSafeYouTubeCaptionUrl(rawUrl);
  const response = await fetch(url.toString(), {
    ...init,
    redirect: 'manual',
  });

  if (response.status >= 300 && response.status < 400) {
    if (redirectsRemaining <= 0) {
      throw new Error('Too many YouTube caption redirects');
    }
    const location = response.headers.get('location');
    if (!location) {
      throw new Error('YouTube caption redirect missing location');
    }
    return fetchYouTubeCaptionUrl(new URL(location, url).toString(), init, redirectsRemaining - 1);
  }

  return response;
}

/**
 * Fetch the transcript for a YouTube video.
 *
 * Strategy:
 *   1. Use yt-dlp to download subtitles (handles YouTube's anti-bot protections)
 *   2. Parse VTT format into segments
 *   3. Get video metadata via yt-dlp JSON
 */
export async function fetchTranscript(
  videoIdOrUrl: string,
  preferredLang?: string,
  options: TranscriptFetchOptions = {},
): Promise<TranscriptResult | null> {
  const videoId = extractVideoId(videoIdOrUrl);
  if (!videoId) {
    logger.warn({
      inputFingerprint: contentLogFingerprint(videoIdOrUrl),
      inputChars: videoIdOrUrl.length,
    }, 'Could not extract video ID');
    return null;
  }

  const lang = preferredLang || 'en';

  try {
    throwIfTranscriptFetchAborted(options.abortSignal);
    // Use yt-dlp to fetch subtitles + metadata
    const result = await fetchWithYtDlp(videoId, lang, options.abortSignal);
    if (result) return result;

    throwIfTranscriptFetchAborted(options.abortSignal);
    logger.info({ videoFingerprint: contentLogFingerprint(videoId) }, 'yt-dlp failed, trying HTTP fallback');
    return await fetchWithHttp(videoId, lang, options.abortSignal);
  } catch (err) {
    throwIfTranscriptFetchAborted(options.abortSignal);
    logger.error({
      ...safeContentLogErrorFields(err),
      videoFingerprint: contentLogFingerprint(videoId),
    }, 'Transcript fetch failed');
    return null;
  }
}

/**
 * Primary method: use yt-dlp to fetch subtitles.
 */
async function fetchWithYtDlp(
  videoId: string,
  lang: string,
  abortSignal?: AbortSignal,
): Promise<TranscriptResult | null> {
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'yt-sub-'));
  const outTemplate = path.join(tmpDir, 'sub');

  try {
    // Step 1: Get video metadata
    const { stdout: metaJson } = await execFileAsync(YT_DLP_PATH, [
      '--dump-json', '--no-download',
      `https://www.youtube.com/watch?v=${videoId}`,
    ], { timeout: 30000, maxBuffer: 10 * 1024 * 1024, signal: abortSignal });

    const meta = JSON.parse(metaJson);
    const title = meta.title || '';
    const channelName = meta.channel || meta.uploader || '';
    const durationSeconds = meta.duration || 0;

    // Step 2: Download subtitles
    const subArgs = [
      '--skip-download',
      '--sub-lang', lang,
      '--sub-format', 'vtt',
      '-o', outTemplate,
      `https://www.youtube.com/watch?v=${videoId}`,
    ];

    // Try manual subs first, then auto
    const hasManualSubs = meta.subtitles && meta.subtitles[lang];
    if (hasManualSubs) {
      subArgs.splice(0, 0, '--write-sub');
    } else {
      subArgs.splice(0, 0, '--write-auto-sub');
    }

    await execFileAsync(YT_DLP_PATH, subArgs, { timeout: 30000, signal: abortSignal });

    // Find the VTT file
    const files = fs.readdirSync(tmpDir).filter(f => f.endsWith('.vtt'));
    if (files.length === 0) {
      logger.info({ videoFingerprint: contentLogFingerprint(videoId) }, 'yt-dlp: no subtitle file produced');
      return null;
    }

    const vttContent = fs.readFileSync(path.join(tmpDir, files[0]), 'utf-8');
    const segments = parseVttCaptions(vttContent);

    if (segments.length === 0) return null;

    const isAutoGenerated = !hasManualSubs;
    const detectedLang = files[0].match(/\.(\w+)\.vtt$/)?.[1] || lang;

    logger.info({
      videoFingerprint: contentLogFingerprint(videoId),
      titleChars: title.length,
      language: detectedLang,
      segments: segments.length,
      isAutoGenerated,
      method: 'yt-dlp',
    }, 'Transcript fetched successfully');

    return {
      videoId,
      title,
      channelName,
      language: detectedLang,
      segments,
      fullText: segments.map(s => s.text).join(' '),
      durationSeconds,
      isAutoGenerated,
    };
  } catch (err) {
    throwIfTranscriptFetchAborted(abortSignal);
    logger.debug({
      ...safeContentLogErrorFields(err),
      videoFingerprint: contentLogFingerprint(videoId),
    }, 'yt-dlp subtitle fetch failed');
    return null;
  } finally {
    // Cleanup temp files
    try { fs.rmSync(tmpDir, { recursive: true, force: true }); } catch { /* ignore */ }
  }
}

/**
 * Fallback: fetch transcript via HTTP (works when YouTube doesn't block captions).
 */
async function fetchWithHttp(
  videoId: string,
  lang: string,
  abortSignal?: AbortSignal,
): Promise<TranscriptResult | null> {
  try {
    const pageUrl = `https://www.youtube.com/watch?v=${videoId}`;
    const pageRes = await fetch(pageUrl, {
      signal: abortSignal,
      headers: {
        'User-Agent': USER_AGENT,
        'Accept-Language': 'en-US,en;q=0.9',
        'Cookie': 'CONSENT=YES+cb.20210328-17-p0.en+FX+999',
      },
    });

    if (!pageRes.ok) return null;
    const html = await pageRes.text();

    const playerResponse = extractPlayerResponse(html);
    if (!playerResponse) return null;

    const videoDetails = playerResponse.videoDetails || {};
    const title = videoDetails.title || '';
    const channelName = videoDetails.author || '';
    const durationSeconds = parseInt(videoDetails.lengthSeconds || '0', 10);

    const captionTracks = playerResponse.captions
      ?.playerCaptionsTracklistRenderer?.captionTracks;
    if (!captionTracks?.length) return null;

    const track = pickBestTrack(captionTracks, lang);
    if (!track?.baseUrl) return null;

    const isAutoGenerated = track.kind === 'asr' ||
      (track.name?.simpleText || '').toLowerCase().includes('auto');
    const language = track.languageCode || 'unknown';

    // Try fetching captions
    const captionRes = await fetchYouTubeCaptionUrl(track.baseUrl, {
      signal: abortSignal,
      headers: { 'User-Agent': USER_AGENT },
    });
    if (!captionRes.ok) return null;

    const xml = await captionRes.text();
    if (!xml || xml.length < 10) return null;

    const segments = parseXmlCaptions(xml);
    if (segments.length === 0) return null;

    return {
      videoId, title, channelName, language, segments,
      fullText: segments.map(s => s.text).join(' '),
      durationSeconds, isAutoGenerated,
    };
  } catch {
    throwIfTranscriptFetchAborted(abortSignal);
    return null;
  }
}

/**
 * Parse WebVTT captions into segments.
 */
function parseVttCaptions(vtt: string): TranscriptSegment[] {
  const segments: TranscriptSegment[] = [];
  const cueRegex = /(\d{2}:\d{2}:\d{2}\.\d{3})\s+-->\s+(\d{2}:\d{2}:\d{2}\.\d{3})[^\n]*\n([\s\S]*?)(?=\n\n|\n\d{2}:\d{2}|$)/g;
  let match: RegExpExecArray | null;
  const seen = new Set<string>(); // Deduplicate repeated lines

  while ((match = cueRegex.exec(vtt)) !== null) {
    const startTime = parseVttTimestamp(match[1]);
    const endTime = parseVttTimestamp(match[2]);
    // Strip VTT tags like <c>, position info, etc.
    const text = match[3]
      .replace(/<[^>]*>/g, '')
      .replace(/\n/g, ' ')
      .trim();

    if (!text || seen.has(text)) continue;
    seen.add(text);

    segments.push({
      text,
      start: startTime,
      duration: endTime - startTime,
    });
  }

  return segments;
}

function parseVttTimestamp(ts: string): number {
  const parts = ts.split(':');
  const h = parseInt(parts[0], 10);
  const m = parseInt(parts[1], 10);
  const s = parseFloat(parts[2]);
  return h * 3600 + m * 60 + s;
}

// ─── Internal Helpers ────────────────────────────────────────────────

/**
 * Extract ytInitialPlayerResponse from the page HTML.
 * YouTube embeds this as a JS variable in the page source.
 */
function extractPlayerResponse(html: string): any | null {
  // Primary pattern: var ytInitialPlayerResponse = {...};
  const patterns = [
    /var\s+ytInitialPlayerResponse\s*=\s*(\{.+?\})\s*;/s,
    /ytInitialPlayerResponse\s*=\s*(\{.+?\})\s*;/s,
    // Fallback: embedded in ytcfg.set or script tags
    /"playerResponse"\s*:\s*"(.+?)"/,
  ];

  for (const pattern of patterns) {
    const match = html.match(pattern);
    if (match?.[1]) {
      try {
        // The third pattern returns escaped JSON string
        if (pattern.source.includes('playerResponse')) {
          const unescaped = match[1]
            .replace(/\\"/g, '"')
            .replace(/\\\\/g, '\\')
            .replace(/\\n/g, '\n');
          return JSON.parse(unescaped);
        }
        return JSON.parse(match[1]);
      } catch {
        continue;
      }
    }
  }

  // Last resort: look for captions data in the raw HTML
  const captionsMatch = html.match(/"captionTracks"\s*:\s*(\[.+?\])/);
  if (captionsMatch) {
    try {
      const tracks = JSON.parse(captionsMatch[1]);
      return { captions: { playerCaptionsTracklistRenderer: { captionTracks: tracks } } };
    } catch { /* fall through */ }
  }

  return null;
}

/**
 * Pick the best caption track based on preference:
 *   1. Manual captions in preferred language
 *   2. Auto-generated in preferred language
 *   3. Manual captions in English
 *   4. Auto-generated in English
 *   5. Any manual captions
 *   6. Any auto-generated captions
 */
function pickBestTrack(
  tracks: any[],
  preferredLang?: string,
): any | null {
  const lang = preferredLang?.toLowerCase() || 'en';

  // Categorize tracks
  const manual: any[] = [];
  const auto: any[] = [];

  for (const t of tracks) {
    if (t.kind === 'asr' || (t.name?.simpleText || '').toLowerCase().includes('auto')) {
      auto.push(t);
    } else {
      manual.push(t);
    }
  }

  // Priority search
  const find = (list: any[], langCode: string) =>
    list.find((t) => (t.languageCode || '').toLowerCase().startsWith(langCode));

  return (
    find(manual, lang) ||
    find(auto, lang) ||
    find(manual, 'en') ||
    find(auto, 'en') ||
    manual[0] ||
    auto[0] ||
    null
  );
}

/**
 * Parse YouTube's JSON3 caption format into segments.
 */
function parseCaptionsJson3(data: any): TranscriptSegment[] {
  const events = data?.events;
  if (!Array.isArray(events)) return [];

  const segments: TranscriptSegment[] = [];

  for (const event of events) {
    if (!event.segs) continue;

    const text = event.segs
      .map((seg: any) => seg.utf8 || '')
      .join('')
      .replace(/\n/g, ' ')
      .trim();

    if (!text) continue;

    segments.push({
      text,
      start: (event.tStartMs || 0) / 1000,
      duration: (event.dDurationMs || 0) / 1000,
    });
  }

  return segments;
}

/**
 * Fallback: Fetch and parse XML captions.
 */
async function fetchCaptionsXml(
  baseUrl: string,
  videoId: string,
  title: string,
  channelName: string,
  language: string,
  isAutoGenerated: boolean,
  durationSeconds: number,
): Promise<TranscriptResult | null> {
  try {
    const res = await fetchYouTubeCaptionUrl(baseUrl, {
      headers: { 'User-Agent': USER_AGENT },
    });
    if (!res.ok) return null;

    const xml = await res.text();
    const segments = parseXmlCaptions(xml);

    if (segments.length === 0) return null;

    return {
      videoId,
      title,
      channelName,
      language,
      segments,
      fullText: segments.map((s) => s.text).join(' '),
      durationSeconds,
      isAutoGenerated,
    };
  } catch {
    return null;
  }
}

/**
 * Parse YouTube's XML caption format.
 * Format: <transcript><text start="0.0" dur="2.5">Hello world</text>...</transcript>
 */
function parseXmlCaptions(xml: string): TranscriptSegment[] {
  const segments: TranscriptSegment[] = [];
  const regex = /<text\s+start="([\d.]+)"\s+dur="([\d.]+)"[^>]*>(.*?)<\/text>/gs;
  let match: RegExpExecArray | null;

  while ((match = regex.exec(xml)) !== null) {
    const text = decodeXmlEntities(match[3])
      .replace(/<[^>]*>/g, '')   // Strip any inner HTML tags
      .replace(/\n/g, ' ')
      .trim();

    if (!text) continue;

    segments.push({
      text,
      start: parseFloat(match[1]),
      duration: parseFloat(match[2]),
    });
  }

  return segments;
}

/**
 * Decode common XML/HTML entities.
 */
function decodeXmlEntities(text: string): string {
  return text
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&#(\d+);/g, (_, num) => String.fromCharCode(parseInt(num, 10)));
}

// ─── Transcript Formatting ──────────────────────────────────────────

/**
 * Format a transcript into timestamped blocks for display or analysis.
 * Groups segments into ~30 second blocks for readability.
 */
export function formatTranscriptTimestamped(
  segments: TranscriptSegment[],
  blockDurationSec = 30,
): string {
  if (segments.length === 0) return '(No transcript available)';

  const blocks: string[] = [];
  let currentBlock: string[] = [];
  let blockStart = 0;

  for (const seg of segments) {
    if (seg.start - blockStart >= blockDurationSec && currentBlock.length > 0) {
      const ts = formatTimestamp(blockStart);
      blocks.push(`[${ts}] ${currentBlock.join(' ')}`);
      currentBlock = [];
      blockStart = seg.start;
    }
    currentBlock.push(seg.text);
  }

  if (currentBlock.length > 0) {
    const ts = formatTimestamp(blockStart);
    blocks.push(`[${ts}] ${currentBlock.join(' ')}`);
  }

  return blocks.join('\n');
}

/**
 * Extract just the first N seconds of transcript (for hook analysis).
 */
export function getHookSection(segments: TranscriptSegment[], durationSec = 30): string {
  const hookSegments = segments.filter((s) => s.start <= durationSec);
  return hookSegments.map((s) => s.text).join(' ');
}

/**
 * Split transcript into sections based on pauses or topic shifts.
 * Returns sections with their start timestamps.
 */
export function splitIntoSections(
  segments: TranscriptSegment[],
  sectionDurationSec = 120,
): { start: number; text: string }[] {
  const sections: { start: number; text: string }[] = [];
  let currentSection: string[] = [];
  let sectionStart = 0;

  for (const seg of segments) {
    if (seg.start - sectionStart >= sectionDurationSec && currentSection.length > 0) {
      sections.push({ start: sectionStart, text: currentSection.join(' ') });
      currentSection = [];
      sectionStart = seg.start;
    }
    currentSection.push(seg.text);
  }

  if (currentSection.length > 0) {
    sections.push({ start: sectionStart, text: currentSection.join(' ') });
  }

  return sections;
}

function formatTimestamp(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return `${m}:${s.toString().padStart(2, '0')}`;
}

// ─── Batch Transcript Fetching (for channel analysis) ────────────────

/**
 * Fetch transcripts for multiple videos, with rate limiting.
 * Returns a map of videoId → transcript text (truncated to maxCharsPerVideo).
 * Only succeeds for videos that have captions — silently skips the rest.
 */
export async function fetchBatchTranscripts(
  videoIds: string[],
  maxCharsPerVideo = 8000,
  delayBetweenMs = 1500,
): Promise<Map<string, { fullText: string; hookText: string; title: string }>> {
  const results = new Map<string, { fullText: string; hookText: string; title: string }>();

  for (const videoId of videoIds) {
    try {
      const transcript = await fetchTranscript(videoId);
      if (transcript && transcript.fullText.length > 50) {
        results.set(videoId, {
          fullText: transcript.fullText.substring(0, maxCharsPerVideo),
          hookText: getHookSection(transcript.segments, 30),
          title: transcript.title,
        });
      }
    } catch (err) {
      logger.debug({
        ...safeContentLogErrorFields(err),
        videoFingerprint: contentLogFingerprint(videoId),
      }, 'Transcript fetch failed for video (non-critical)');
    }

    // Rate limit between fetches
    if (delayBetweenMs > 0) {
      await new Promise((r) => setTimeout(r, delayBetweenMs));
    }
  }

  logger.info({ requested: videoIds.length, fetched: results.size }, 'Batch transcript fetch complete');
  return results;
}
