#!/usr/bin/env bash
# ─────────────────────────────────────────────────────
# release-identity.sh — Generate release identity from git, never hand-typed
#
# Modes:
#   markdown                     → table for pasting into a release doc (default)
#   json                         → JSON for programmatic consumption
#   --persist                    → write JSON to docs/release/release-identity.json
#                                   AND markdown to docs/release/release-identity.md
#                                   (atomic via tmp+rename)
#   --persist --quiet            → as --persist but no stdout
#
# Combined with the new pre-commit injection (release-pipeline-risk-based-
# optimization, 2026-05-03), edits to the workspace canonical release docs
# can refer to "see docs/release/release-identity.md" instead of typing
# SHAs by hand. This eliminates the literal-SHA + literal-test-count
# drift class entirely.
# ─────────────────────────────────────────────────────
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IOS_REPO="${IOS_REPO:-/Users/felipedominguez/Desktop/Nexus Hub IOS/Nexus Hub}"
WORKSPACE_DOCS_ROOT="${NEXUS_WORKSPACE_DOCS_ROOT:-/Users/felipedominguez/Desktop/Nexus Hub}"
FORMAT="${1:-markdown}"
PERSIST=false
QUIET=false

while [ $# -gt 0 ]; do
  case "$1" in
    --persist) PERSIST=true; shift;;
    --quiet)   QUIET=true;   shift;;
    json|--json|markdown|--markdown) FORMAT="$1"; shift;;
    *) shift;;
  esac
done

branch_for() {
  git -C "$1" branch --show-current 2>/dev/null || printf 'unknown'
}

sha_for() {
  git -C "$1" rev-parse --short HEAD 2>/dev/null || printf 'unknown'
}

dirty_for() {
  if [ ! -e "$1/.git" ]; then
    printf 'unknown'
    return
  fi
  if [ -n "$(git -C "$1" status --short)" ]; then
    printf 'dirty'
  else
    printf 'clean'
  fi
}

version_for() {
  if [ -f "$1/package.json" ]; then
    node -p "require('$1/package.json').version" 2>/dev/null || printf 'unknown'
  else
    printf 'n/a'
  fi
}

migration_count_for() {
  if [ -d "$1/migrations" ]; then
    find "$1/migrations" -type f -name '*.sql' | wc -l | tr -d ' '
  else
    printf 'n/a'
  fi
}

timestamp="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
backend_branch="$(branch_for "$ROOT")"
backend_sha="$(sha_for "$ROOT")"
backend_dirty="$(dirty_for "$ROOT")"
backend_version="$(version_for "$ROOT")"
backend_migrations="$(migration_count_for "$ROOT")"

ios_branch="$(branch_for "$IOS_REPO")"
ios_sha="$(sha_for "$IOS_REPO")"
ios_dirty="$(dirty_for "$IOS_REPO")"

render_json() {
  node <<JSON
const payload = {
  generatedAt: "$timestamp",
  backend: {
    path: "$ROOT",
    branch: "$backend_branch",
    commit: "$backend_sha",
    dirtyState: "$backend_dirty",
    packageVersion: "$backend_version",
    migrationCount: "$backend_migrations"
  },
  ios: {
    path: "$IOS_REPO",
    branch: "$ios_branch",
    commit: "$ios_sha",
    dirtyState: "$ios_dirty"
  }
};
console.log(JSON.stringify(payload, null, 2));
JSON
}

render_markdown() {
  cat <<EOF
| Area | Path | Branch | Commit | Dirty state | Version | Migrations |
| --- | --- | --- | --- | --- | --- | --- |
| Backend | \`$ROOT\` | \`$backend_branch\` | \`$backend_sha\` | \`$backend_dirty\` | \`$backend_version\` | \`$backend_migrations\` |
| iOS | \`$IOS_REPO\` | \`$ios_branch\` | \`$ios_sha\` | \`$ios_dirty\` | n/a | n/a |

Generated at: \`$timestamp\`
EOF
}

# Persist artifacts atomically (tmp file + mv). Both formats are written so
# pre-commit / docs can pick whichever format they need.
persist_artifacts() {
  local docs_dir="$WORKSPACE_DOCS_ROOT/docs/release"
  if [ ! -d "$docs_dir" ]; then
    docs_dir="$ROOT/docs/release"
  fi
  mkdir -p "$docs_dir" 2>/dev/null || true
  local json_path="$docs_dir/release-identity.json"
  local md_path="$docs_dir/release-identity.md"
  local tmp_json="$json_path.tmp.$$"
  local tmp_md="$md_path.tmp.$$"

  render_json > "$tmp_json"
  {
    echo "<!-- Generated by scripts/release-identity.sh — do NOT hand-edit. -->"
    echo "<!-- Re-run \`engine/scripts/release-identity.sh --persist\` to refresh. -->"
    echo
    echo "# Release Identity"
    echo
    render_markdown
  } > "$tmp_md"

  mv "$tmp_json" "$json_path"
  mv "$tmp_md" "$md_path"

  if [ "$QUIET" = false ]; then
    echo "📝 Persisted release identity:" >&2
    echo "    $json_path" >&2
    echo "    $md_path" >&2
  fi
}

if [ "$PERSIST" = true ]; then
  persist_artifacts
  if [ "$QUIET" = true ]; then
    exit 0
  fi
fi

case "$FORMAT" in
  json|--json) render_json ;;
  markdown|--markdown) render_markdown ;;
  *)
    echo "Usage: scripts/release-identity.sh [markdown|json] [--persist] [--quiet]" >&2
    exit 64
    ;;
esac
