import { vi } from 'vitest';

const nullFn = () => null;
const falseFn = () => false;
const emptyArrayFn = () => [];

export const getUserByTelegramId = vi.fn(nullFn);
export const getOwnerBootstrapTelegramId = vi.fn(nullFn);
export const assertOwnerBootstrapReadyForRuntime = vi.fn();
export const isOwnerBootstrapTelegramId = vi.fn(falseFn);
export const getOrCreateUser = vi.fn(nullFn);
export const getUserById = vi.fn(nullFn);
export const resolveCanonicalUserId = vi.fn(nullFn);
export const getOwnerBootstrapUser = vi.fn(nullFn);
export const getOwnerBootstrapTarget = vi.fn(nullFn);
export const getOwnerBootstrapUserRefs = vi.fn(emptyArrayFn);
export const getOrCreateInviteSandboxUser = vi.fn(nullFn);
export const resolveIosInviteRegistrationTarget = vi.fn(() => ({ mode: 'invalid' }));
export const isOwnerUserRef = vi.fn(falseFn);
export const sanitizeDisplayName = vi.fn((value: string | null | undefined) => value?.trim() || '');
export const getPreferredDisplayName = vi.fn(() => 'User');
export const getPreferredDisplayNameById = vi.fn(() => 'User');
export const getUserByAppleId = vi.fn(nullFn);
export const getUserByGoogleId = vi.fn(nullFn);
export const getUserByEmail = vi.fn(nullFn);
export const createAppleUser = vi.fn(nullFn);
export const createGoogleUser = vi.fn(nullFn);
export const createEmailUser = vi.fn(nullFn);
export const emitProviderLinkedAudit = vi.fn();
export const isUserAuthorized = vi.fn(falseFn);
export const isOwner = vi.fn(falseFn);
export const touchUser = vi.fn();
export const getUserLanguage = vi.fn(() => 'pt-BR');
export const getUserLanguageById = vi.fn(() => 'pt-BR');
export const getUserTimezone = vi.fn(() => 'Europe/Lisbon');
export const getUserTimezoneById = vi.fn(() => 'Europe/Lisbon');
export const setUserLanguage = vi.fn();
export const listUsers = vi.fn(emptyArrayFn);
export const listUsersInternal = vi.fn(emptyArrayFn);
export const setUserStatus = vi.fn();
export const setUserStatusById = vi.fn();
export const setUserTier = vi.fn();
export const setUserLimits = vi.fn();
export const createInviteCode = vi.fn(() => 'TEST-CODE');
export const validateAndConsumeInviteCode = vi.fn(() => ({ valid: false }));
export const listInviteCodes = vi.fn(emptyArrayFn);
export const deleteInviteCode = vi.fn(falseFn);
export const seedOwnerUser = vi.fn();
