// Copyright (c) 2025 Felipe Dominguez. MIT License. See LICENSE.

import { describe, expect, it, vi } from 'vitest';
import fs from 'fs';
import path from 'path';
import {
  createPasswordResetPageHandler,
  registerPortalStaticRoutes,
} from '../../src/portal/static-routes';

/**
 * Pin tests for the static password-reset destination page route.
 *
 * Shipped 2026-05-04 to close the AUTH-O2 follow-up gap: the email
 * link generated by `/api/v1/auth/password-reset/request` had no
 * destination because `https://app.nexushub.me/auth/password-reset` —
 * the placeholder default — never resolved. The backend now serves
 * the destination page itself at `/auth/password-reset` from the same
 * origin as the API.
 *
 * These tests pin the contract operator playbooks rely on:
 *   1. The route exists and is mounted at the path the email points to.
 *   2. The handler returns 200 + HTML when the file exists.
 *   3. The handler returns 503 (not 404, not 500) when the file is
 *      missing — same shape as the landing-preview handler so a
 *      stale build is operator-visible.
 *   4. The response sets the same restrictive security headers as the
 *      admin dashboard, plus `frame-ancestors 'none'` so the page
 *      cannot be iframe'd by a phishing site that proxies the token.
 */

function fakeRequest(): any {
  return {};
}

function fakeResponse() {
  const headers: Record<string, string> = {};
  let statusCode = 200;
  let body: string | undefined;
  let contentType: string | undefined;
  return {
    res: {
      set: vi.fn((k: string, v: string) => {
        headers[k] = v;
      }),
      type: vi.fn((t: string) => {
        contentType = t;
        return {
          send: vi.fn((b: string) => {
            body = b;
          }),
        };
      }),
      status: vi.fn((c: number) => {
        statusCode = c;
        return {
          send: vi.fn((b: string) => {
            body = b;
          }),
        };
      }),
    },
    snapshot: () => ({ headers, statusCode, body, contentType }),
  };
}

describe('password reset page route', () => {
  const portalDir = path.join(__dirname, '..', '..', 'src', 'portal');

  it('serves password-reset.html with a 200 + html content type when the file is present', () => {
    const handler = createPasswordResetPageHandler(portalDir);
    const fr = fakeResponse();

    handler(fakeRequest(), fr.res as any);

    const snap = fr.snapshot();
    expect(snap.contentType).toBe('html');
    expect(snap.statusCode).toBe(200);
    expect(snap.body).toBeDefined();
    expect(snap.body!).toContain('Reset your password');
    // The token is stripped client-side via history.replaceState in the
    // page script, which the strict CSP serves from /portal/ui. Pin the
    // served asset (not the HTML, whose comment would keep a gutted script
    // green) so a copy-paste mistake cannot ship the page without it.
    expect(snap.body!).toContain('<script src="/portal/ui/auth-password-reset.js"></script>');
    const pageScript = fs.readFileSync(path.join(portalDir, 'ui', 'auth-password-reset.js'), 'utf8');
    expect(pageScript).toContain('history.replaceState');
  });

  it('returns 503 when the page file is missing (operator-visible build drift)', () => {
    const handler = createPasswordResetPageHandler('/nonexistent/dir/that/should/not/exist');
    const fr = fakeResponse();

    handler(fakeRequest(), fr.res as any);

    const snap = fr.snapshot();
    expect(snap.statusCode).toBe(503);
    expect(snap.body).toMatch(/Password reset page not deployed/i);
  });

  it('sets restrictive security headers (no caching, no framing, strict CSP)', () => {
    const handler = createPasswordResetPageHandler(portalDir);
    const fr = fakeResponse();

    handler(fakeRequest(), fr.res as any);

    const { headers } = fr.snapshot();
    expect(headers['Cache-Control']).toBe('no-cache, no-store, must-revalidate');
    expect(headers['X-Frame-Options']).toBe('DENY');
    expect(headers['X-Content-Type-Options']).toBe('nosniff');
    expect(headers['Referrer-Policy']).toBe('no-referrer');
    expect(headers['Content-Security-Policy']).toContain("default-src 'self'");
    expect(headers['Content-Security-Policy']).toContain("frame-ancestors 'none'");
    expect(headers['Content-Security-Policy']).toContain("connect-src 'self'");
    expect(headers['Content-Security-Policy']).toContain("form-action 'self'");
  });

  it('mounts the handler at /auth/password-reset', () => {
    const registered: { path: string; handler: any }[] = [];
    const fakeApp = {
      get: vi.fn((p: string, h: any) => {
        registered.push({ path: p, handler: h });
      }),
    } as any;

    registerPortalStaticRoutes(fakeApp, portalDir);

    const passwordResetRoute = registered.find((r) => r.path === '/auth/password-reset');
    expect(passwordResetRoute).toBeDefined();
    // Sanity: same admin routes still registered alongside it (dashboard
    // root + /admin + /portal + /landing-preview).
    expect(registered.find((r) => r.path === '/landing-preview')).toBeDefined();
    expect(registered.find((r) => r.path === '/')).toBeDefined();
    expect(registered.find((r) => r.path === '/admin')).toBeDefined();
    expect(registered.find((r) => r.path === '/portal')).toBeDefined();
  });
});
